### ISSUE TITLE
Question: Documenting prereqs?

### ISSUE THREAD

**Issue by jchauncey** [deis/docs-v2#24]
Where should we document the prerequisites of v2? Such as daemonsets. It seems like a separate section

**Comment by bacongobbler** [comment]
https://github.com/deis/docs-v2/blob/master/src/installing-deis/quickstart.md#choose-a-provider is where users go to read for installing the kubernetes cluster, so it'd probably be best to leave a note there. Either that or in https://github.com/deis/docs-v2/blob/master/src/installing-deis/system-requirements.md.

**Comment by jchauncey** [comment]
fixed via #28
