### ISSUE TITLE
Doc how to deploy from private repos and private registries?  Maybe...

### ISSUE THREAD

**Issue by krancour** [deis/docs-v2#67]
This line about being able to deploy from a private registry probably isn't entirely correct-- at least not without additional steps having been taken:

https://github.com/deis/docs-v2/blame/master/src/using-deis/using-docker-images.md#L46-L47

The question of deployment from private registries or from private repositories in public registries has been raised before.  Just one such example: https://github.com/deis/deis/issues/4756

Per the thread I referenced, I think we can support such scenarios, but that it requires the docker daemon on each host to be pre-authenticated to the registries in question.  This isn't documented anywhere currently.

This is definitely an endeavor only for more advanced operators.  Do we want to document it?  Or does this fall into the realm of things we don't _officially_ support or endorse?  Should we just change "private" to "public" [here](https://github.com/deis/docs-v2/blame/master/src/using-deis/using-docker-images.md#L46-L47) and then wait until we've build Docker auth into workflow itself?

**Comment by rimusz** [comment]
We definitely should support private repos and registries in v2

@krancour cannot we use http://kubernetes.io/v1.1/docs/user-guide/images.html#specifying-imagepullsecrets-on-a-pod

**Comment by krancour** [comment]
@rimusz that sounds like a good alternative to managing that at the host level.  +1

Support for that would still need to be built into workflow to be useful.

So question is what, if anything should the docs say about this topic currently?

**Comment by rimusz** [comment]
@krancour currently we should explain the available host level option
When we have it's support in Workflow then we will change the docs

**Comment by bacongobbler** [comment]
I think all are good options, however we should be testing these workflows first before documenting them. I'd err on the side of leaving this out for now until we confirm one of these workflows will work. Perhaps we can point users interested in this feature to the issue/possible solutions for them to try out, but I don't think solidifying any concrete documentation on "this is how you do it" will work.

**Comment by slack** [comment]
Private registry support using PullSecrets is top of the list for 2.1.

Until then, private registry support will always be a workaround, don't think we should doc it per-se.

**Comment by krancour** [comment]
@slack so should this line change for now?

https://github.com/deis/docs-v2/blame/master/src/using-deis/using-docker-images.md#L46-L47
