### ISSUE TITLE
Proposal: Remove add/remove hosts page

### ISSUE THREAD

**Issue by krancour** [deis/docs-v2#73]
This page (a placeholder) may not be relevant at all.  There is no procedure for adding or removing Workflow hosts that is above or beyond the procedure for adding or removing hosts to/from the underlying k8s cluster.

https://github.com/deis/docs-v2/blob/master/src/managing-workflow/adding-or-removing-hosts.md

I propose it be removed.  All in favor?

**Comment by mboersma** [comment]
Aye, aye, cap'n. Throw that page overboard.
