### ISSUE TITLE
Nearly every diagram requires updating

### ISSUE THREAD

**Issue by krancour** [deis/docs-v2#8]
Most diagrams are inaccurate.  Some contain mentions of things such as etcd, fleet, and deisctl.  Some express relationships between components that no longer exist.  For instance, the logger does not depend on the store anymore.

**Comment by jchauncey** [comment]
I am using monodraw for my diagram of the logger system btw. Since its ascii art its easy to paste into markdown.

**Comment by bacongobbler** [comment]
ping @gabrtv -- what was the software you used to make the original diagrams again?

**Comment by jchauncey** [comment]
my guess is something like omnigraffle.

**Comment by bacongobbler** [comment]
Ah! That was the name. He used LucidChart.

**Comment by slack** [comment]
I've got some suitable replacements for the diagrams.

**Comment by krancour** [comment]
Is it maybe possible that we could start a repository of diagrams?  Not exported pngs or whatever, but the actual source files for whatever was used-- Omnigraffle, for instance?

**Comment by slack** [comment]
Sure thing.
